#pragma once

#define PCT_MOUSE_BUTTON_1         0
#define PCT_MOUSE_BUTTON_2         1
#define PCT_MOUSE_BUTTON_3         2
#define PCT_MOUSE_BUTTON_4         3
#define PCT_MOUSE_BUTTON_5         4
#define PCT_MOUSE_BUTTON_6         5
#define PCT_MOUSE_BUTTON_7         6
#define PCT_MOUSE_BUTTON_8         7
#define PCT_MOUSE_BUTTON_LAST      PCT_MOUSE_BUTTON_8
#define PCT_MOUSE_BUTTON_LEFT      PCT_MOUSE_BUTTON_1
#define PCT_MOUSE_BUTTON_RIGHT     PCT_MOUSE_BUTTON_2
#define PCT_MOUSE_BUTTON_MIDDLE    PCT_MOUSE_BUTTON_3